### PR TITLE
Missing tests - Adding two missing tests and re-ordering existing tests.

### PR DESCRIPTION
**Pull request by karandesai-96**
* I recently started using this library for practicing implementation of some algorithms and I decided to run some tests. I saw the tests were a little bit un-ordered so it was difficult to keep track. 

* The files in directory are arranged in alphabetical order and so if the tests are too arranged in that way, it is better to analyze the code for a third person viewing it.

* So I have ordered the tests in each file alphabetically, and on the way I discovered that two tests were not written - bogo sort, and primality test. I have added them in too.

* I develop in Pycharm IDE by Jetbrains community, and nowadays many python users do so. This IDE generates a `.idea/` directory which does not need to be on Github, so I also updated the gitignore file in the PR.

* I do not intend to do more work in the PR unless there are issues with the current code written here. So if the checks pass and the reviewer feels it is proper, this PR is fit to be merged. :+1:

### CODE REVIEW

**Comment by karandesai-96** [comment]
I am getting some ideas for impementation of an algorithm which can be a good addition to the lib. This lib is great as far as the code is concerned, I intend to contribute and open up more PRs further. :smile:

**Comment by karandesai-96** [comment]
Oops, got a little `AssertionError`, will fix it in a commit.

**Comment by karandesai-96** [comment]
Only Python3.2 check fails. I don't know why.
@nryoung Please review this and help me find the problem. :smiley:

**Comment by nryoung** [comment]
The reason this test is failing is because `virtualenv `>= 14.x no longer supports py3.2. I have fixed this issue in master. Can you rebase your branch with master? If you need help with rebasing checkout: https://github.com/edx/edx-platform/wiki/How-to-Rebase-a-Pull-Request

**Comment by karandesai-96** [comment]
Well, that was smooth.. now fit to be merged ! :+1: 

If I find a good algorithm to implement, I will send a new PR soon, it was pleasure using your library and working with it ! :smile:

**Comment by karandesai-96** [comment]
@nryoung Please review it :)

**Comment by karandesai-96** [comment]
@nryoung this will get stale, please suggest workarounds :smile:

**Comment by nryoung** [comment]
@karandesai-96 This is still on my radar to review. Don't worry about it getting stale. I will get to it soon.

**Comment by karandesai-96** [comment]
Cool. Whenever you get to it. If there is any test remaining, please let me know -- I will push a commit in no time. :smiley:

**Comment by nryoung** [comment]
Thank you for your contribution! These changes look solid, just have one comment:

Can you squash and rebase your commits to a single commit with a short but descriptive commit message about your changes. Take a look at: https://github.com/edx/edx-platform/wiki/How-to-Rebase-a-Pull-Request if you need help.

**Comment by karandesai-96** [comment]
Sure, I will do it right away.

**Comment by karandesai-96** [comment]
@nryoung I was away for a while. I did as you said, all commits squashed in two commits, but one:
* First commit includes change in .gitignore. I kept it separate so that it helps to track this change easily when `git blame` is used in future.
* Second commit has all test files related changes.

**Comment by karandesai-96** [comment]
@nryoung A gentle reminder :smile:

**Comment by nryoung** [comment]
This looks good! Thank you for the hard work.

**Comment by karandesai-96** [comment]
Thank you :smile:

**Pull request merged**
