### PR TITLE
Testing codecov.io

### PR DESCRIPTION
**Pull request by nryoung**

### CODE REVIEW

**Comment by stevepeak** [comment]
I this method does not work you may need to call Codecov from inside your tox env, [read more why here](https://github.com/rackerlabs/mimic/pull/427#issuecomment-142523645). Let me know if you need help if it does not work  :)

**Comment by nryoung** [comment]
@stevepeak yep, I noticed that this was still not working correctly. You may want to look at: https://github.com/tomchristie/django-rest-framework/tree/master implementation as I was using it as a reference. If you look at their build status on Travis CI they are throwing the same errors as me: https://travis-ci.org/tomchristie/django-rest-framework

**Comment by nryoung** [comment]
@stevepeak, actually once I fix it up here, I will open a PR on DRF to fix it up there.

**Comment by stevepeak** [comment]
@nryoung thank you! Let me know if there is any help I can provide.

**Pull request merged**
